# Generated by Django 4.2.6 on 2023-10-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adult',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_franchise',
            field=models.BooleanField(),
        ),
    ]
